import { FoodItem } from '../types';

export const localFoodDatabase: FoodItem[] = [
  // ─── FRUITS ───────────────────────────────────────────────────────────────
  { id: 'db_f1',  name: 'Apple (Medium)',       brand: 'Generic', servingSize: 182, servingUnit: 'g', calories: 95,  protein: 0.5, carbs: 25,  fats: 0.3, fiber: 4.4, sugar: 19 },
  { id: 'db_f2',  name: 'Banana (Medium)',      brand: 'Generic', servingSize: 118, servingUnit: 'g', calories: 105, protein: 1.3, carbs: 27,  fats: 0.4, fiber: 3.1, sugar: 14 },
  { id: 'db_f3',  name: 'Blueberries',          brand: 'Generic', servingSize: 148, servingUnit: 'g', calories: 84,  protein: 1.1, carbs: 21,  fats: 0.5, fiber: 3.6, sugar: 15 },
  { id: 'db_f4',  name: 'Strawberries',         brand: 'Generic', servingSize: 152, servingUnit: 'g', calories: 49,  protein: 1.0, carbs: 12,  fats: 0.5, fiber: 3.0, sugar: 7 },
  { id: 'db_f5',  name: 'Orange (Medium)',      brand: 'Generic', servingSize: 131, servingUnit: 'g', calories: 62,  protein: 1.2, carbs: 15,  fats: 0.2, fiber: 3.1, sugar: 12 },
  { id: 'db_f6',  name: 'Watermelon',           brand: 'Generic', servingSize: 280, servingUnit: 'g', calories: 85,  protein: 1.7, carbs: 21,  fats: 0.4, fiber: 1.1, sugar: 17 },
  { id: 'db_f7',  name: 'Grapes (Red)',         brand: 'Generic', servingSize: 151, servingUnit: 'g', calories: 104, protein: 1.1, carbs: 27,  fats: 0.2, fiber: 1.4, sugar: 23 },
  { id: 'db_f8',  name: 'Pineapple',            brand: 'Generic', servingSize: 165, servingUnit: 'g', calories: 82,  protein: 0.9, carbs: 22,  fats: 0.2, fiber: 2.3, sugar: 16 },
  { id: 'db_f9',  name: 'Mango',                brand: 'Generic', servingSize: 165, servingUnit: 'g', calories: 99,  protein: 1.4, carbs: 25,  fats: 0.6, fiber: 2.6, sugar: 22 },
  { id: 'db_f10', name: 'Raspberries',          brand: 'Generic', servingSize: 123, servingUnit: 'g', calories: 64,  protein: 1.5, carbs: 15,  fats: 0.8, fiber: 8.0, sugar: 5 },
  { id: 'db_f11', name: 'Peach (Medium)',       brand: 'Generic', servingSize: 150, servingUnit: 'g', calories: 58,  protein: 1.4, carbs: 14,  fats: 0.4, fiber: 2.3, sugar: 13 },
  { id: 'db_f12', name: 'Cherries (Sweet)',     brand: 'Generic', servingSize: 138, servingUnit: 'g', calories: 87,  protein: 1.5, carbs: 22,  fats: 0.3, fiber: 2.9, sugar: 18 },
  { id: 'db_f13', name: 'Kiwi',                 brand: 'Generic', servingSize: 69,  servingUnit: 'g', calories: 42,  protein: 0.8, carbs: 10,  fats: 0.4, fiber: 2.1, sugar: 6 },

  // ─── VEGETABLES ────────────────────────────────────────────────────────────
  { id: 'db_v1',  name: 'Broccoli (Raw)',       brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 34,  protein: 2.8, carbs: 6.6, fats: 0.4, fiber: 2.6 },
  { id: 'db_v2',  name: 'Spinach (Raw)',        brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 23,  protein: 2.9, carbs: 3.6, fats: 0.4, fiber: 2.2 },
  { id: 'db_v3',  name: 'Carrots (Raw)',        brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 41,  protein: 0.9, carbs: 9.6, fats: 0.2, fiber: 2.8 },
  { id: 'db_v4',  name: 'Tomato (Raw)',         brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 18,  protein: 0.9, carbs: 3.9, fats: 0.2, fiber: 1.2 },
  { id: 'db_v5',  name: 'Cucumber (Raw)',       brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 15,  protein: 0.7, carbs: 3.6, fats: 0.1, fiber: 0.5 },
  { id: 'db_v6',  name: 'Bell Pepper (Red)',    brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 31,  protein: 1.0, carbs: 6.0, fats: 0.3, fiber: 2.1 },
  { id: 'db_v7',  name: 'Onion (Raw)',          brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 40,  protein: 1.1, carbs: 9.3, fats: 0.1, fiber: 1.7 },
  { id: 'db_v8',  name: 'Asparagus (Cooked)',  brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 22,  protein: 2.4, carbs: 4.1, fats: 0.2, fiber: 2.1 },
  { id: 'db_v9',  name: 'Cauliflower (Raw)',    brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 25,  protein: 1.9, carbs: 5.0, fats: 0.3, fiber: 2.0 },
  { id: 'db_v10', name: 'Zucchini (Raw)',       brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 17,  protein: 1.2, carbs: 3.1, fats: 0.3, fiber: 1.0 },
  { id: 'db_v11', name: 'Kale (Raw)',           brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 49,  protein: 4.3, carbs: 9.0, fats: 0.9, fiber: 3.6 },
  { id: 'db_v12', name: 'Mushrooms (White)',    brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 22,  protein: 3.1, carbs: 3.3, fats: 0.3, fiber: 1.0 },
  { id: 'db_v13', name: 'Brussels Sprouts',     brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 43,  protein: 3.4, carbs: 9.0, fats: 0.3, fiber: 3.8 },
  { id: 'db_v14', name: 'Edamame (Shelled)',    brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 121, protein: 11.9,carbs: 8.9, fats: 5.2, fiber: 5.2 },
  { id: 'db_v15', name: 'Green Beans',          brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 31,  protein: 1.8, carbs: 7.0, fats: 0.1, fiber: 2.7 },
  { id: 'db_v16', name: 'Celery (Raw)',         brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 16,  protein: 0.7, carbs: 3.0, fats: 0.2, fiber: 1.6 },
  { id: 'db_v17', name: 'Beet (Raw)',           brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 43,  protein: 1.6, carbs: 10,  fats: 0.2, fiber: 2.8 },
  { id: 'db_v18', name: 'Arugula (Raw)',        brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 25,  protein: 2.6, carbs: 3.7, fats: 0.7, fiber: 1.6 },

  // ─── PROTEINS (MEAT, POULTRY, FISH) ──────────────────────────────────────
  { id: 'db_p1',  name: 'Chicken Breast (Raw)', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 165, protein: 31,  carbs: 0,   fats: 3.6 },
  { id: 'db_p2',  name: 'Chicken Thigh (Raw)',  brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 177, protein: 20,  carbs: 0,   fats: 10 },
  { id: 'db_p3',  name: 'Chicken Breast (Cooked)', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 165, protein: 31, carbs: 0, fats: 3.6 },
  { id: 'db_p4',  name: 'Ground Beef 90% Lean', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 176, protein: 20,  carbs: 0,   fats: 10 },
  { id: 'db_p5',  name: 'Ground Beef 80% Lean', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 254, protein: 17,  carbs: 0,   fats: 20 },
  { id: 'db_p6',  name: 'Steak (Sirloin, Raw)', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 244, protein: 27,  carbs: 0,   fats: 15 },
  { id: 'db_p7',  name: 'Pork Tenderloin',      brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 143, protein: 26,  carbs: 0,   fats: 3.5 },
  { id: 'db_p8',  name: 'Turkey Breast (Raw)',  brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 104, protein: 24,  carbs: 0,   fats: 1.5 },
  { id: 'db_p9',  name: 'Salmon (Raw)',          brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 208, protein: 20,  carbs: 0,   fats: 13 },
  { id: 'db_p10', name: 'Tuna (Canned in Water)',brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 90,  protein: 20,  carbs: 0,   fats: 1 },
  { id: 'db_p11', name: 'Tilapia (Raw)',         brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 96,  protein: 20,  carbs: 0,   fats: 1.7 },
  { id: 'db_p12', name: 'Shrimp (Cooked)',       brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 99,  protein: 24,  carbs: 0.2, fats: 0.3 },
  { id: 'db_p13', name: 'Cod (Raw)',             brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 82,  protein: 18,  carbs: 0,   fats: 0.7 },
  { id: 'db_p14', name: 'Lean Pork Chop',        brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 187, protein: 29,  carbs: 0,   fats: 7.0 },
  { id: 'db_p15', name: 'Deli Turkey Breast',    brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 30,  protein: 5.5, carbs: 0.5, fats: 0.5 },
  { id: 'db_p16', name: 'Rotisserie Chicken (Breast)', brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 168, protein: 28, carbs: 0, fats: 5 },
  { id: 'db_p17', name: 'Mahi Mahi (Raw)',       brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 85,  protein: 18.5,carbs: 0,   fats: 0.7 },
  { id: 'db_p18', name: 'Bison (Ground, Raw)',   brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 146, protein: 21,  carbs: 0,   fats: 7 },

  // ─── DAIRY & EGGS ─────────────────────────────────────────────────────────
  { id: 'db_d1',  name: 'Egg (Whole, Large)',    brand: 'Generic', servingSize: 50,  servingUnit: 'g', calories: 72,  protein: 6,   carbs: 0.4, fats: 4.8 },
  { id: 'db_d2',  name: 'Egg Whites (Liquid)',   brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 54,  protein: 11,  carbs: 0.7, fats: 0.2 },
  { id: 'db_d3',  name: 'Milk (Whole)',          brand: 'Generic', servingSize: 240, servingUnit: 'ml',calories: 149, protein: 8,   carbs: 12,  fats: 8 },
  { id: 'db_d4',  name: 'Milk (2%)',             brand: 'Generic', servingSize: 240, servingUnit: 'ml',calories: 122, protein: 8,   carbs: 12,  fats: 4.8 },
  { id: 'db_d5',  name: 'Milk (Skim)',           brand: 'Generic', servingSize: 240, servingUnit: 'ml',calories: 83,  protein: 8,   carbs: 12,  fats: 0.2 },
  { id: 'db_d6',  name: 'Greek Yogurt (Non-Fat, Plain)', brand: 'Generic', servingSize: 170, servingUnit: 'g', calories: 100, protein: 18, carbs: 6, fats: 0 },
  { id: 'db_d7',  name: 'Greek Yogurt (Full Fat)', brand: 'Generic', servingSize: 170, servingUnit: 'g', calories: 190, protein: 17, carbs: 6, fats: 10 },
  { id: 'db_d8',  name: 'Cheddar Cheese',        brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 114, protein: 7,   carbs: 0.4, fats: 9.4 },
  { id: 'db_d9',  name: 'Mozzarella (Low Fat)',  brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 72,  protein: 6.9, carbs: 0.8, fats: 4.5 },
  { id: 'db_d10', name: 'Cottage Cheese (2%)',   brand: 'Generic', servingSize: 113, servingUnit: 'g', calories: 92,  protein: 12,  carbs: 5,   fats: 2.5 },
  { id: 'db_d11', name: 'Butter (Salted)',        brand: 'Generic', servingSize: 14,  servingUnit: 'g', calories: 102, protein: 0.1, carbs: 0,   fats: 11.5 },
  { id: 'db_d12', name: 'Cream Cheese',          brand: 'Generic', servingSize: 30,  servingUnit: 'g', calories: 99,  protein: 1.7, carbs: 1.2, fats: 9.8 },
  { id: 'db_d13', name: 'Parmesan (Grated)',     brand: 'Generic', servingSize: 15,  servingUnit: 'g', calories: 57,  protein: 5.2, carbs: 0.2, fats: 3.7 },

  // ─── GRAINS, PASTA & CARBS ────────────────────────────────────────────────
  { id: 'db_c1',  name: 'White Rice (Cooked)',   brand: 'Generic', servingSize: 158, servingUnit: 'g', calories: 205, protein: 4.3, carbs: 45,  fats: 0.4, fiber: 0.6 },
  { id: 'db_c2',  name: 'Brown Rice (Cooked)',   brand: 'Generic', servingSize: 195, servingUnit: 'g', calories: 216, protein: 5.0, carbs: 45,  fats: 1.8, fiber: 3.5 },
  { id: 'db_c3',  name: 'Rolled Oats (Dry)',     brand: 'Generic', servingSize: 40,  servingUnit: 'g', calories: 152, protein: 5,   carbs: 27,  fats: 3,   fiber: 4 },
  { id: 'db_c4',  name: 'Quinoa (Cooked)',       brand: 'Generic', servingSize: 185, servingUnit: 'g', calories: 222, protein: 8.1, carbs: 39,  fats: 3.6, fiber: 5.2 },
  { id: 'db_c5',  name: 'Pasta (Cooked)',        brand: 'Generic', servingSize: 140, servingUnit: 'g', calories: 220, protein: 8,   carbs: 43,  fats: 1.3, fiber: 2.5 },
  { id: 'db_c6',  name: 'Whole Wheat Bread',     brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 69,  protein: 3.6, carbs: 11.6,fats: 1.1, fiber: 1.9 },
  { id: 'db_c7',  name: 'White Bread',           brand: 'Generic', servingSize: 25,  servingUnit: 'g', calories: 67,  protein: 2.1, carbs: 13,  fats: 0.8, fiber: 0.6 },
  { id: 'db_c8',  name: 'Sweet Potato (Baked)',  brand: 'Generic', servingSize: 114, servingUnit: 'g', calories: 103, protein: 2.3, carbs: 24,  fats: 0.2, fiber: 3.8 },
  { id: 'db_c9',  name: 'Potato (White, Baked)', brand: 'Generic', servingSize: 173, servingUnit: 'g', calories: 161, protein: 4.3, carbs: 37,  fats: 0.2, fiber: 3.8 },
  { id: 'db_c10', name: 'Corn (Yellow)',         brand: 'Generic', servingSize: 154, servingUnit: 'g', calories: 177, protein: 5.4, carbs: 41,  fats: 2.1, fiber: 4.6 },
  { id: 'db_c11', name: 'Farro (Cooked)',        brand: 'Generic', servingSize: 200, servingUnit: 'g', calories: 200, protein: 8,   carbs: 40,  fats: 1.5, fiber: 7 },
  { id: 'db_c12', name: 'Barley (Cooked)',       brand: 'Generic', servingSize: 157, servingUnit: 'g', calories: 193, protein: 3.5, carbs: 44,  fats: 0.7, fiber: 6 },
  { id: 'db_c13', name: 'Tortilla (Flour, 8")',  brand: 'Generic', servingSize: 45,  servingUnit: 'g', calories: 146, protein: 3.9, carbs: 25,  fats: 3.5, fiber: 1.5 },
  { id: 'db_c14', name: 'Tortilla (Corn, 6")',   brand: 'Generic', servingSize: 26,  servingUnit: 'g', calories: 58,  protein: 1.5, carbs: 12,  fats: 0.7, fiber: 1.4 },
  { id: 'db_c15', name: 'Bagel (Plain)',         brand: 'Generic', servingSize: 105, servingUnit: 'g', calories: 270, protein: 10,  carbs: 53,  fats: 1.5, fiber: 2 },
  { id: 'db_c16', name: 'Granola (Low-Fat)',     brand: 'Generic', servingSize: 59,  servingUnit: 'g', calories: 220, protein: 5,   carbs: 47,  fats: 2.8, fiber: 3.4 },

  // ─── NUTS, SEEDS & OILS ──────────────────────────────────────────────────
  { id: 'db_n1',  name: 'Almonds',              brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 164, protein: 6,   carbs: 6,   fats: 14, fiber: 3.5 },
  { id: 'db_n2',  name: 'Walnuts',              brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 185, protein: 4.3, carbs: 3.9, fats: 18.5, fiber: 1.9 },
  { id: 'db_n3',  name: 'Peanut Butter (Natural)', brand: 'Generic', servingSize: 32, servingUnit: 'g', calories: 188, protein: 8, carbs: 6, fats: 16, fiber: 1.9 },
  { id: 'db_n4',  name: 'Almond Butter',        brand: 'Generic', servingSize: 32,  servingUnit: 'g', calories: 196, protein: 6.8, carbs: 6,   fats: 18 },
  { id: 'db_n5',  name: 'Olive Oil (Extra Virgin)', brand: 'Generic', servingSize: 14, servingUnit: 'g', calories: 119, protein: 0, carbs: 0, fats: 13.5 },
  { id: 'db_n6',  name: 'Avocado',              brand: 'Generic', servingSize: 100, servingUnit: 'g', calories: 160, protein: 2,   carbs: 8.5, fats: 14.7, fiber: 6.7 },
  { id: 'db_n7',  name: 'Chia Seeds',           brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 138, protein: 4.7, carbs: 12,  fats: 8.7, fiber: 9.8 },
  { id: 'db_n8',  name: 'Flaxseed (Ground)',    brand: 'Generic', servingSize: 14,  servingUnit: 'g', calories: 75,  protein: 2.6, carbs: 4.1, fats: 5.9, fiber: 3.8 },
  { id: 'db_n9',  name: 'Cashews',              brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 157, protein: 5.2, carbs: 9.3, fats: 12.4 },
  { id: 'db_n10', name: 'Sunflower Seeds',      brand: 'Generic', servingSize: 28,  servingUnit: 'g', calories: 166, protein: 5.8, carbs: 5.6, fats: 14.4 },
  { id: 'db_n11', name: 'Coconut Oil',          brand: 'Generic', servingSize: 14,  servingUnit: 'g', calories: 121, protein: 0,   carbs: 0,   fats: 13.5 },
  { id: 'db_n12', name: 'Tahini (Sesame Paste)', brand: 'Generic', servingSize: 15, servingUnit: 'g', calories: 89,  protein: 2.6, carbs: 3.2, fats: 8 },

  // ─── LEGUMES ─────────────────────────────────────────────────────────────
  { id: 'db_l1',  name: 'Chickpeas (Canned)',   brand: 'Generic', servingSize: 164, servingUnit: 'g', calories: 269, protein: 14.5,carbs: 45,  fats: 4.2, fiber: 12.5 },
  { id: 'db_l2',  name: 'Black Beans (Cooked)', brand: 'Generic', servingSize: 172, servingUnit: 'g', calories: 227, protein: 15.2,carbs: 41,  fats: 0.9, fiber: 15 },
  { id: 'db_l3',  name: 'Lentils (Cooked)',     brand: 'Generic', servingSize: 198, servingUnit: 'g', calories: 230, protein: 17.9,carbs: 40,  fats: 0.8, fiber: 15.6 },
  { id: 'db_l4',  name: 'Kidney Beans (Canned)', brand: 'Generic', servingSize: 128, servingUnit: 'g', calories: 218, protein: 14, carbs: 40, fats: 0.9, fiber: 11.3 },
  { id: 'db_l5',  name: 'Pinto Beans (Cooked)', brand: 'Generic', servingSize: 171, servingUnit: 'g', calories: 245, protein: 15.4,carbs: 45,  fats: 1.1, fiber: 15.4 },
  { id: 'db_l6',  name: 'Hummus',               brand: 'Generic', servingSize: 60,  servingUnit: 'g', calories: 108, protein: 3,   carbs: 10,  fats: 6.4, fiber: 2.4 },

  // ─── BRANDED / SUPPLEMENTS ───────────────────────────────────────────────
  { id: 'db_b1',  name: 'Whey Protein Powder',  brand: 'Optimum Nutrition', servingSize: 31, servingUnit: 'g', calories: 120, protein: 24, carbs: 3, fats: 1 },
  { id: 'db_b2',  name: 'Casein Protein Powder', brand: 'Optimum Nutrition', servingSize: 34, servingUnit: 'g', calories: 120, protein: 24, carbs: 4, fats: 1 },
  { id: 'db_b3',  name: 'Quest Protein Bar',     brand: 'Quest', servingSize: 60, servingUnit: 'g', calories: 200, protein: 21, carbs: 22, fats: 7, fiber: 14 },
  { id: 'db_b4',  name: 'RX Bar',               brand: 'RX Bar', servingSize: 52, servingUnit: 'g', calories: 210, protein: 12, carbs: 24, fats: 9, fiber: 5 },
  { id: 'db_b5',  name: 'Clif Bar',             brand: 'Clif', servingSize: 68, servingUnit: 'g', calories: 250, protein: 9, carbs: 44, fats: 6, fiber: 5 },
  { id: 'db_b6',  name: 'Monster Zero Ultra',   brand: 'Monster', servingSize: 473, servingUnit: 'ml', calories: 10, protein: 0, carbs: 2, fats: 0 },
  { id: 'db_b7',  name: 'Almond Milk (Unsweetened)', brand: 'Almond Breeze', servingSize: 240, servingUnit: 'ml', calories: 30, protein: 1, carbs: 1, fats: 2.5 },
  { id: 'db_b8',  name: 'Oat Milk (Barista)',   brand: 'Oatly', servingSize: 240, servingUnit: 'ml', calories: 130, protein: 3, carbs: 20, fats: 4 },
  { id: 'db_b9',  name: 'Rice Cakes (Lightly Salted)', brand: 'Quaker', servingSize: 9, servingUnit: 'g', calories: 35, protein: 1, carbs: 7, fats: 0 },
  { id: 'db_b10', name: 'Kind Bar (Almond Coconut)', brand: 'Kind', servingSize: 40, servingUnit: 'g', calories: 200, protein: 4, carbs: 16, fats: 14, fiber: 3 },
  { id: 'db_b11', name: 'Fairlife Core Power 42g', brand: 'Fairlife', servingSize: 414, servingUnit: 'ml', calories: 230, protein: 42, carbs: 9, fats: 3.5 },
  { id: 'db_b12', name: 'G Zero Gatorade',       brand: 'Gatorade', servingSize: 591, servingUnit: 'ml', calories: 10, protein: 0, carbs: 2, fats: 0 },

  // ─── RESTAURANT FAST FOOD ────────────────────────────────────────────────
  { id: 'db_r1',  name: 'Big Mac',              brand: 'McDonalds', servingSize: 219, servingUnit: 'g', calories: 550, protein: 25, carbs: 45, fats: 30 },
  { id: 'db_r2',  name: 'French Fries (Medium)',brand: 'McDonalds', servingSize: 111, servingUnit: 'g', calories: 320, protein: 5, carbs: 43, fats: 15 },
  { id: 'db_r3',  name: 'McDouble',             brand: 'McDonalds', servingSize: 177, servingUnit: 'g', calories: 400, protein: 22, carbs: 34, fats: 20 },
  { id: 'db_r4',  name: 'Chicken Sandwich',     brand: 'Chick-fil-A', servingSize: 165, servingUnit: 'g', calories: 420, protein: 28, carbs: 41, fats: 18 },
  { id: 'db_r5',  name: 'Burrito Bowl (Chicken)', brand: 'Chipotle', servingSize: 400, servingUnit: 'g', calories: 630, protein: 40, carbs: 65, fats: 21 },
  { id: 'db_r6',  name: 'Crunchwrap Supreme',   brand: 'Taco Bell', servingSize: 255, servingUnit: 'g', calories: 530, protein: 16, carbs: 71, fats: 21 },
  { id: 'db_r7',  name: 'Subway 6" Turkey Sub', brand: 'Subway', servingSize: 237, servingUnit: 'g', calories: 280, protein: 18, carbs: 40, fats: 4.5 },
  { id: 'db_r8',  name: 'Starbucks Latte (Tall)', brand: 'Starbucks', servingSize: 354, servingUnit: 'ml', calories: 150, protein: 9, carbs: 15, fats: 6 },
  { id: 'db_r9',  name: 'Starbucks Cold Brew',  brand: 'Starbucks', servingSize: 473, servingUnit: 'ml', calories: 5, protein: 0.3, carbs: 1, fats: 0 },
  { id: 'db_r10', name: 'Panda Express Orange Chicken', brand: 'Panda Express', servingSize: 159, servingUnit: 'g', calories: 380, protein: 14, carbs: 45, fats: 18 },

  // ─── SNACKS ──────────────────────────────────────────────────────────────
  { id: 'db_s1',  name: 'Greek Yogurt (Honey)', brand: 'Fage', servingSize: 150, servingUnit: 'g', calories: 160, protein: 13, carbs: 17, fats: 4.5 },
  { id: 'db_s2',  name: 'Skyr (Plain)',         brand: 'Siggi', servingSize: 150, servingUnit: 'g', calories: 100, protein: 17, carbs: 7, fats: 0.5 },
  { id: 'db_s3',  name: 'Almonds (Salted)',     brand: 'Blue Diamond', servingSize: 28, servingUnit: 'g', calories: 170, protein: 6, carbs: 5, fats: 15 },
  { id: 'db_s4',  name: 'Beef Jerky',          brand: 'Jack Links', servingSize: 28, servingUnit: 'g', calories: 80, protein: 12, carbs: 3, fats: 1 },
  { id: 'db_s5',  name: 'String Cheese',       brand: 'Sargento', servingSize: 21, servingUnit: 'g', calories: 80, protein: 8, carbs: 0, fats: 6 },
  { id: 'db_s6',  name: 'Protein Cookie',      brand: 'Lenny & Larry', servingSize: 113, servingUnit: 'g', calories: 420, protein: 16, carbs: 55, fats: 14, fiber: 8 },
  { id: 'db_s7',  name: 'Popcorn (Air-Popped)', brand: 'Generic', servingSize: 28, servingUnit: 'g', calories: 110, protein: 3.6, carbs: 22, fats: 1.3, fiber: 4.3 },
  { id: 'db_s8',  name: 'Dark Chocolate (70%)', brand: 'Generic', servingSize: 28, servingUnit: 'g', calories: 168, protein: 2.2, carbs: 12, fats: 12 },
  { id: 'db_s9',  name: 'Protein Chips',       brand: 'Quest', servingSize: 32, servingUnit: 'g', calories: 120, protein: 20, carbs: 5, fats: 4.5 },

  // ─── BEVERAGES ───────────────────────────────────────────────────────────
  { id: 'db_bev1', name: 'Coffee (Black)',      brand: 'Generic', servingSize: 240, servingUnit: 'ml', calories: 2, protein: 0.3, carbs: 0, fats: 0 },
  { id: 'db_bev2', name: 'Orange Juice',        brand: 'Generic', servingSize: 240, servingUnit: 'ml', calories: 112, protein: 1.7, carbs: 26, fats: 0.5 },
  { id: 'db_bev3', name: 'Coca-Cola (Regular)', brand: 'Coca-Cola', servingSize: 355, servingUnit: 'ml', calories: 140, protein: 0, carbs: 39, fats: 0, sugar: 39 },
  { id: 'db_bev4', name: 'Coca-Cola Zero',      brand: 'Coca-Cola', servingSize: 355, servingUnit: 'ml', calories: 0, protein: 0, carbs: 0, fats: 0 },
  { id: 'db_bev5', name: 'Protein Shake (ready-to-drink)', brand: 'Premier Protein', servingSize: 325, servingUnit: 'ml', calories: 160, protein: 30, carbs: 5, fats: 3 },

  // ─── CONDIMENTS & SAUCES ─────────────────────────────────────────────────
  { id: 'db_cond1', name: 'Ketchup',           brand: 'Heinz', servingSize: 17, servingUnit: 'g', calories: 20, protein: 0, carbs: 5, fats: 0, sugar: 4 },
  { id: 'db_cond2', name: 'Mustard (Yellow)',  brand: 'French\'s', servingSize: 5, servingUnit: 'g', calories: 3, protein: 0.2, carbs: 0.3, fats: 0.2 },
  { id: 'db_cond3', name: 'Hot Sauce',         brand: 'Tabasco', servingSize: 5, servingUnit: 'ml', calories: 0, protein: 0, carbs: 0.1, fats: 0 },
  { id: 'db_cond4', name: 'Sriracha',          brand: 'Huy Fong', servingSize: 6, servingUnit: 'g', calories: 5, protein: 0.1, carbs: 1, fats: 0 },
  { id: 'db_cond5', name: 'Soy Sauce (Low Sodium)', brand: 'Kikkoman', servingSize: 15, servingUnit: 'ml', calories: 10, protein: 1.5, carbs: 1, fats: 0, sodium: 575 },
  { id: 'db_cond6', name: 'BBQ Sauce',         brand: 'Sweet Baby Rays', servingSize: 36, servingUnit: 'g', calories: 70, protein: 0, carbs: 18, fats: 0, sugar: 16 },
];
